spring:
  application:
    name: Apple Sales Assistant
  profiles:
    include: db

llm:
  provider: ollama        # or ollama
  system-prompt: classpath:prompts/system_prompt.txt

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  timeout-seconds: 60
  model: llama3.2:latest

openai:
  api-key: ${OPENAI_API_KEY}                # set in env
  base-url: https://api.openai.com
  model: gpt-4o-mini
  timeout-seconds: 60

security:
  jwt:
    issuer: sales-assistant
    secret: ${JWT_SECRET:dev-please-change-this-32+chars}
    expires-minutes: 60

kb:
  file-path: classpath:kb/kb.txt
  chunk-size: 700        # soft limit; chunks split again if too long
  top-k: 4               # how many chunks to include in context

